### ISSUE TITLE
server应该填什么？

### ISSUE THREAD

**Issue by dxxxkit** [ferrinweb/voice-input-button#2]
没有明白server的地方应该填什么，请问可以解释一下吗

**Comment by ferrinweb** [comment]
因为讯飞语音相关接口都执行白名单策略，仅在白名单的 ip 发送来的请求能被处理。为了使你的终端设备能够使用讯飞的语音接口，你需要自己部署一个代理服务器，将代理服务器的 ip 配置到你的讯飞账号语音听写应用的白名单设置中。

这个代理服务器负责将终端的语音请求转发给讯飞语音接口。这里的 server 地址就是你的服务器代理的地址。**源码中的 proxy 目录就是一个 node 代理服务器样例，可以直接部署或者供你参考。**
